name: Deploy backend infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/**'
      - 'services/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: true
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.OIDC_ROLE_BACKEND_DEPLOY_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Lambda code zip and upload
        working-directory: services/lambda-visitor-counter
        run: |
          zip -r lambda_visitor_counter.zip .
          aws s3 cp lambda_visitor_counter.zip s3://${{ vars.LAMBDA_BUCKET_NAME }}/lambda_visitor_counter.zip
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2
      
      - name: Terraform init
        working-directory: infrastructure
        run: |          
          terraform fmt -recursive
          terraform init -reconfigure

      - name: Terraform plan
        working-directory: infrastructure
        run: |
          terraform plan -out=tfplan

      - name: Upload Terraform plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan

      - name: Terraform apply
        working-directory: infrastructure
        run: |          
          terraform apply -auto-approve tfplan