name: Deploy frontend to S3

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.OIDC_ROLE_FRONTEND_DEPLOY_ARN }} 
          aws-region: ${{ vars.AWS_REGION }}
      
      - name: Deploy to S3
        run: |
          aws s3 sync frontend s3://${{ vars.FRONTEND_BUCKET_NAME }} --delete
