name: Deploy backend infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/**'
      - 'services/**'

permissions:
  id-token: write
  contents: read
    
jobs:
  deploy:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.OIDC_ROLE_BACKEND_DEPLOY_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Lambda code zip and upload
        run: |
          cd services/lambda-visitor-counter
          zip -r lambda_visitor_counter.zip .
          aws s3 cp lambda_visitor_counter.zip s3://${{ vars.LAMBDA_BUCKET_NAME }}/lambda_visitor_counter.zip
      
      - name: Terraform init
        run: |
          cd infrastructure
          terraform fmt -recursive
          terraform init

      - name: Terraform plan
        run: |
          cd infrastructure
          terraform plan

      - name: Terraform apply
        run: |
          cd infrastructure
          terraform apply -auto-approve


